//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the first name to proceed..
        /// </summary>
        internal static string _sms001 {
            get {
                return ResourceManager.GetString("_sms001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the last name to proceed..
        /// </summary>
        internal static string _sms002 {
            get {
                return ResourceManager.GetString("_sms002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email to proceed..
        /// </summary>
        internal static string _sms003 {
            get {
                return ResourceManager.GetString("_sms003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your desired username to proceed..
        /// </summary>
        internal static string _sms004 {
            get {
                return ResourceManager.GetString("_sms004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password to proceed..
        /// </summary>
        internal static string _sms005 {
            get {
                return ResourceManager.GetString("_sms005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm password to proceed..
        /// </summary>
        internal static string _sms006 {
            get {
                return ResourceManager.GetString("_sms006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a security question to proceed..
        /// </summary>
        internal static string _sms007 {
            get {
                return ResourceManager.GetString("_sms007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide answer to the question to proceed..
        /// </summary>
        internal static string _sms008 {
            get {
                return ResourceManager.GetString("_sms008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Characters are not allowed..
        /// </summary>
        internal static string _sms009 {
            get {
                return ResourceManager.GetString("_sms009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid E-Mail ID..
        /// </summary>
        internal static string _sms010 {
            get {
                return ResourceManager.GetString("_sms010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the &quot;A-Z&quot;,&quot;a-z&quot;,&quot;0-9&quot;,&quot;.&quot;,&quot;_&quot; are allowed..
        /// </summary>
        internal static string _sms011 {
            get {
                return ResourceManager.GetString("_sms011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the &quot;A-Z&quot;,&quot;a-z&quot;,&quot;0-9&quot; are allowed..
        /// </summary>
        internal static string _sms012 {
            get {
                return ResourceManager.GetString("_sms012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Does not Match..
        /// </summary>
        internal static string _sms013 {
            get {
                return ResourceManager.GetString("_sms013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Re-Enter Username and Password..
        /// </summary>
        internal static string _sms014 {
            get {
                return ResourceManager.GetString("_sms014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss.
        /// </summary>
        internal static string ss {
            get {
                return ResourceManager.GetString("ss", resourceCulture);
            }
        }
    }
}
